# Generated by Django 4.2.27 on 2025-12-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Année de l'événement", verbose_name="Année"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titre court de l'événement",
                        max_length=200,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "description_short",
                    models.TextField(
                        help_text="Description en 2-3 phrases, niveau collège",
                        verbose_name="Description courte",
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        choices=[
                            ("chapter_1", "Précurseurs & Pionniers (1800-1960)"),
                            ("chapter_2", "Programmes & Systèmes experts (1960-1990)"),
                            ("chapter_3", "Grandes victoires (1990-2010)"),
                            ("chapter_4", "Deep Learning & IA génératives (2010-...)"),
                        ],
                        help_text="Chapitre de l'histoire de l'IA",
                        max_length=20,
                        verbose_name="Chapitre",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "Facile"), (2, "Moyen"), (3, "Difficile")],
                        default=1,
                        help_text="Niveau de difficulté (1-3)",
                        verbose_name="Difficulté",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste de tags pour catégoriser l'événement",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "people",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Personnes associées à l'événement",
                        verbose_name="Personnalités",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL optionnelle d'une image illustrative",
                        null=True,
                        verbose_name="URL de l'image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["year"],
            },
        ),
    ]
