# Generated by Django 4.2.27 on 2026-01-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0002_alter_event_created_at_alter_event_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Encadré 'Le savais-tu ?' pour le mode découverte",
                null=True,
                verbose_name="Explication pédagogique",
            ),
        ),
    ]
