# Generated by Django 4.2.27 on 2026-01-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0003_event_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL optionnelle d'une image illustrative",
                max_length=500,
                null=True,
                verbose_name="URL de l'image",
            ),
        ),
    ]
