# Generated by Django 4.2.27 on 2026-01-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0004_alter_event_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="chapter",
            field=models.CharField(
                choices=[("chapter_1", "L'Aventure de l'IA (1843-2024)")],
                help_text="Chapitre de l'histoire de l'IA",
                max_length=20,
                verbose_name="Chapitre",
            ),
        ),
    ]
