# Generated by Django 4.2.27 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0005_alter_event_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("chapter_1", "Les pionniers (1843-1955)"),
                    ("chapter_2", "L'âge d'or des symboles (1956-1980)"),
                    ("chapter_3", "L'hiver et le renouveau (1980-2010)"),
                    ("chapter_4", "L'IA moderne (2010-aujourd'hui)"),
                ],
                help_text="Chapitre de l'histoire de l'IA",
                max_length=20,
                verbose_name="Chapitre",
            ),
        ),
    ]
